# Generated by Django 4.1.6 on 2023-04-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phoneNumber',
        ),
    ]
