# Generated by Django 4.1.6 on 2023-04-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicSalary', models.FloatField()),
                ('coefficientPay', models.FloatField()),
                ('coefficientAllowance', models.FloatField()),
            ],
            options={
                'db_table': 'level_salaries',
            },
        ),
    ]
