# Generated by Django 4.2 on 2023-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminapp",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
