# Generated by Django 4.1.7 on 2023-04-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_adminapp_managers_remove_adminapp_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapp',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
