# Generated by Django 4.1.7 on 2023-04-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_phonenumber'),
        ('admins', '0004_alter_adminapp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapp',
            name='employee',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
